repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11.7
        types: [python, yaml, json]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [javascript, html, css]
  
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  
    hooks:
      - id: flake8