[tool.black]
line-length = 120
target-version = ['py311']
extend-exclude = '''
/(
    \.git
 | \.hg
 | \.mypy_cache
 | \.tox
 | \.venv
 | _build
 | buck-out
 | build
)/
'''
yaml-include = """\.ya?ml$"""